// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messenger/src/messenger.proto

package com.messenger.protobuf;

public final class MessengerProto {
  private MessengerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code messengerproto.MessageType}
   */
  public static final class MessageType extends
      com.google.protobuf.GeneratedMessage
      implements MessageTypeOrBuilder {
    // Use MessageType.newBuilder() to construct.
    private MessageType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageType defaultInstance;
    public static MessageType getDefaultInstance() {
      return defaultInstance;
    }

    public MessageType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messenger.protobuf.MessengerProto.MessageType.class, com.messenger.protobuf.MessengerProto.MessageType.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageType> PARSER =
        new com.google.protobuf.AbstractParser<MessageType>() {
      public MessageType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageType(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageType> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.messenger.protobuf.MessengerProto.MessageType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messengerproto.MessageType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.messenger.protobuf.MessengerProto.MessageType.class, com.messenger.protobuf.MessengerProto.MessageType.Builder.class);
      }

      // Construct using com.messenger.protobuf.MessengerProto.MessageType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageType_descriptor;
      }

      public com.messenger.protobuf.MessengerProto.MessageType getDefaultInstanceForType() {
        return com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance();
      }

      public com.messenger.protobuf.MessengerProto.MessageType build() {
        com.messenger.protobuf.MessengerProto.MessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.messenger.protobuf.MessengerProto.MessageType buildPartial() {
        com.messenger.protobuf.MessengerProto.MessageType result = new com.messenger.protobuf.MessengerProto.MessageType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.messenger.protobuf.MessengerProto.MessageType) {
          return mergeFrom((com.messenger.protobuf.MessengerProto.MessageType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.messenger.protobuf.MessengerProto.MessageType other) {
        if (other == com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.messenger.protobuf.MessengerProto.MessageType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.messenger.protobuf.MessengerProto.MessageType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messengerproto.MessageType)
    }

    static {
      defaultInstance = new MessageType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messengerproto.MessageType)
  }

  public interface MessageHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1 [default = 0];
    /**
     * <code>required int32 code = 1 [default = 0];</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1 [default = 0];</code>
     */
    int getCode();

    // required .messengerproto.MessageType messageType = 2;
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    com.messenger.protobuf.MessengerProto.MessageType getMessageType();
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder getMessageTypeOrBuilder();
  }
  /**
   * Protobuf type {@code messengerproto.MessageHeader}
   */
  public static final class MessageHeader extends
      com.google.protobuf.GeneratedMessage
      implements MessageHeaderOrBuilder {
    // Use MessageHeader.newBuilder() to construct.
    private MessageHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageHeader defaultInstance;
    public static MessageHeader getDefaultInstance() {
      return defaultInstance;
    }

    public MessageHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              com.messenger.protobuf.MessengerProto.MessageType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = messageType_.toBuilder();
              }
              messageType_ = input.readMessage(com.messenger.protobuf.MessengerProto.MessageType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageType_);
                messageType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messenger.protobuf.MessengerProto.MessageHeader.class, com.messenger.protobuf.MessengerProto.MessageHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageHeader> PARSER =
        new com.google.protobuf.AbstractParser<MessageHeader>() {
      public MessageHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1 [default = 0];
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1 [default = 0];</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1 [default = 0];</code>
     */
    public int getCode() {
      return code_;
    }

    // required .messengerproto.MessageType messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private com.messenger.protobuf.MessengerProto.MessageType messageType_;
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    public com.messenger.protobuf.MessengerProto.MessageType getMessageType() {
      return messageType_;
    }
    /**
     * <code>required .messengerproto.MessageType messageType = 2;</code>
     */
    public com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder getMessageTypeOrBuilder() {
      return messageType_;
    }

    private void initFields() {
      code_ = 0;
      messageType_ = com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMessageType().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, messageType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, messageType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.messenger.protobuf.MessengerProto.MessageHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messengerproto.MessageHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.messenger.protobuf.MessengerProto.MessageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.messenger.protobuf.MessengerProto.MessageHeader.class, com.messenger.protobuf.MessengerProto.MessageHeader.Builder.class);
      }

      // Construct using com.messenger.protobuf.MessengerProto.MessageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageTypeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (messageTypeBuilder_ == null) {
          messageType_ = com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance();
        } else {
          messageTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_MessageHeader_descriptor;
      }

      public com.messenger.protobuf.MessengerProto.MessageHeader getDefaultInstanceForType() {
        return com.messenger.protobuf.MessengerProto.MessageHeader.getDefaultInstance();
      }

      public com.messenger.protobuf.MessengerProto.MessageHeader build() {
        com.messenger.protobuf.MessengerProto.MessageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.messenger.protobuf.MessengerProto.MessageHeader buildPartial() {
        com.messenger.protobuf.MessengerProto.MessageHeader result = new com.messenger.protobuf.MessengerProto.MessageHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (messageTypeBuilder_ == null) {
          result.messageType_ = messageType_;
        } else {
          result.messageType_ = messageTypeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.messenger.protobuf.MessengerProto.MessageHeader) {
          return mergeFrom((com.messenger.protobuf.MessengerProto.MessageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.messenger.protobuf.MessengerProto.MessageHeader other) {
        if (other == com.messenger.protobuf.MessengerProto.MessageHeader.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMessageType()) {
          mergeMessageType(other.getMessageType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        if (!getMessageType().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.messenger.protobuf.MessengerProto.MessageHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.messenger.protobuf.MessengerProto.MessageHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1 [default = 0];
      private int code_ ;
      /**
       * <code>required int32 code = 1 [default = 0];</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1 [default = 0];</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1 [default = 0];</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1 [default = 0];</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // required .messengerproto.MessageType messageType = 2;
      private com.messenger.protobuf.MessengerProto.MessageType messageType_ = com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.messenger.protobuf.MessengerProto.MessageType, com.messenger.protobuf.MessengerProto.MessageType.Builder, com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder> messageTypeBuilder_;
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public com.messenger.protobuf.MessengerProto.MessageType getMessageType() {
        if (messageTypeBuilder_ == null) {
          return messageType_;
        } else {
          return messageTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(com.messenger.protobuf.MessengerProto.MessageType value) {
        if (messageTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageType_ = value;
          onChanged();
        } else {
          messageTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(
          com.messenger.protobuf.MessengerProto.MessageType.Builder builderForValue) {
        if (messageTypeBuilder_ == null) {
          messageType_ = builderForValue.build();
          onChanged();
        } else {
          messageTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public Builder mergeMessageType(com.messenger.protobuf.MessengerProto.MessageType value) {
        if (messageTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              messageType_ != com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance()) {
            messageType_ =
              com.messenger.protobuf.MessengerProto.MessageType.newBuilder(messageType_).mergeFrom(value).buildPartial();
          } else {
            messageType_ = value;
          }
          onChanged();
        } else {
          messageTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        if (messageTypeBuilder_ == null) {
          messageType_ = com.messenger.protobuf.MessengerProto.MessageType.getDefaultInstance();
          onChanged();
        } else {
          messageTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public com.messenger.protobuf.MessengerProto.MessageType.Builder getMessageTypeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMessageTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      public com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder getMessageTypeOrBuilder() {
        if (messageTypeBuilder_ != null) {
          return messageTypeBuilder_.getMessageOrBuilder();
        } else {
          return messageType_;
        }
      }
      /**
       * <code>required .messengerproto.MessageType messageType = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.messenger.protobuf.MessengerProto.MessageType, com.messenger.protobuf.MessengerProto.MessageType.Builder, com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder> 
          getMessageTypeFieldBuilder() {
        if (messageTypeBuilder_ == null) {
          messageTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.messenger.protobuf.MessengerProto.MessageType, com.messenger.protobuf.MessengerProto.MessageType.Builder, com.messenger.protobuf.MessengerProto.MessageTypeOrBuilder>(
                  messageType_,
                  getParentForChildren(),
                  isClean());
          messageType_ = null;
        }
        return messageTypeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:messengerproto.MessageHeader)
    }

    static {
      defaultInstance = new MessageHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messengerproto.MessageHeader)
  }

  public interface EmptyMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code messengerproto.EmptyMessage}
   */
  public static final class EmptyMessage extends
      com.google.protobuf.GeneratedMessage
      implements EmptyMessageOrBuilder {
    // Use EmptyMessage.newBuilder() to construct.
    private EmptyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EmptyMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EmptyMessage defaultInstance;
    public static EmptyMessage getDefaultInstance() {
      return defaultInstance;
    }

    public EmptyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EmptyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_EmptyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_EmptyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messenger.protobuf.MessengerProto.EmptyMessage.class, com.messenger.protobuf.MessengerProto.EmptyMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<EmptyMessage> PARSER =
        new com.google.protobuf.AbstractParser<EmptyMessage>() {
      public EmptyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmptyMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.messenger.protobuf.MessengerProto.EmptyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.messenger.protobuf.MessengerProto.EmptyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messengerproto.EmptyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.messenger.protobuf.MessengerProto.EmptyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_EmptyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_EmptyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.messenger.protobuf.MessengerProto.EmptyMessage.class, com.messenger.protobuf.MessengerProto.EmptyMessage.Builder.class);
      }

      // Construct using com.messenger.protobuf.MessengerProto.EmptyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.messenger.protobuf.MessengerProto.internal_static_messengerproto_EmptyMessage_descriptor;
      }

      public com.messenger.protobuf.MessengerProto.EmptyMessage getDefaultInstanceForType() {
        return com.messenger.protobuf.MessengerProto.EmptyMessage.getDefaultInstance();
      }

      public com.messenger.protobuf.MessengerProto.EmptyMessage build() {
        com.messenger.protobuf.MessengerProto.EmptyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.messenger.protobuf.MessengerProto.EmptyMessage buildPartial() {
        com.messenger.protobuf.MessengerProto.EmptyMessage result = new com.messenger.protobuf.MessengerProto.EmptyMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.messenger.protobuf.MessengerProto.EmptyMessage) {
          return mergeFrom((com.messenger.protobuf.MessengerProto.EmptyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.messenger.protobuf.MessengerProto.EmptyMessage other) {
        if (other == com.messenger.protobuf.MessengerProto.EmptyMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.messenger.protobuf.MessengerProto.EmptyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.messenger.protobuf.MessengerProto.EmptyMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messengerproto.EmptyMessage)
    }

    static {
      defaultInstance = new EmptyMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messengerproto.EmptyMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messengerproto_MessageType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messengerproto_MessageType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messengerproto_MessageHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messengerproto_MessageHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messengerproto_EmptyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messengerproto_EmptyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035Messenger/src/messenger.proto\022\016messeng" +
      "erproto\"\033\n\013MessageType\022\014\n\004type\030\001 \002(\t\"R\n\r" +
      "MessageHeader\022\017\n\004code\030\001 \002(\005:\0010\0220\n\013messag" +
      "eType\030\002 \002(\0132\033.messengerproto.MessageType" +
      "\"\016\n\014EmptyMessageB(\n\026com.messenger.protob" +
      "ufB\016MessengerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messengerproto_MessageType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messengerproto_MessageType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messengerproto_MessageType_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_messengerproto_MessageHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messengerproto_MessageHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messengerproto_MessageHeader_descriptor,
              new java.lang.String[] { "Code", "MessageType", });
          internal_static_messengerproto_EmptyMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messengerproto_EmptyMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messengerproto_EmptyMessage_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
